Feature: Change PIN
  Customers being issued new cards are supplied with a Personal
  Identification Number (PIN) that is randomly generated by the system.
  In order to be able to change it to something they can easily remember,
  customers with new bank cards need to be able to change their PIN
  using the ATM.

  # A background section in a feature file allows you to specify a set of steps that are common
  # to every scenario in the file.
  # Here are a couple of advantages to doing this:
  # If you ever need to change those steps, you  have to change them in only one place.
  # The importance of those steps  fades into the background so that when you’re reading
  # each individual scenario, you can focus on what is unique and important about that scenario.
  Background:
    # Additional description
  Insert a newly issued card and sign in
  Whenever the bank issues new cards to customers, they are supplied with a
  Personal Identification Number (PIN) that is randomly generated by the system.
    
    Given I have been issued a new card
    And I insert the card, entering the correct PIM
    And I choose "Change the PIN" from the menu

  Scenario: Change PIN successfully
    When I change the PIN to 9876
    Then the system should remember my PIN is now 9876

  Scenario: Try to change PIN to the same as before
    When I try to change the PIN to the original PIN number
    Then I should see a warning message
    And the system should not have to changed my PIN
